### ISSUE TITLE
java.sql.SQLNonTransientConnectionException: No current connection.

### ISSUE THREAD

**Issue by nlmarco** [cloudstore/cloudstore#10]
Sometimes (fortunately very rarely), [this exception happens](https://www.codewizards.co/jenkins/job/co.codewizards.cloudstore/co.codewizards.cloudstore$co.codewizards.cloudstore.core/200/testReport/junit/co.codewizards.cloudstore.core.repo.sync/RepoToRepoSyncTest/syncFromRemoteToLocalWithModifiedFilesWithRemotePathPrefix/):

_java.sql.SQLNonTransientConnectionException: No current connection._

This seems to be a known bug in Derby: https://issues.apache.org/jira/browse/DERBY-6175

**Comment by 354787000** [comment]
china no.1！！

**Comment by ZakariaSouadda** [comment]
FUCK YOU MOTHERFUCKER YOU GOT US CORONA VIRUS YOU DUMB SHIT
