### ISSUE TITLE
Cannot get rid of collisions

### ISSUE THREAD

**Issue by ValdisVitolins** [cloudstore/cloudstore#43]
After renaming folder I get infinite cycle of collisions, and can't delete them. After any synchorization I get new folders named:
Folder.i0h21uyk.collision
Folder.i0gvc5hn.collision.i0gxmwyw.collision
Folder.i0gvc5hn.collision.i0gxmwyw.collision.collision.i0h1rbxg.collision.collision
etc.
What should I do?

**Comment by ValdisVitolins** [comment]
Another case of collisions appeared and now I noticed that it happened because synchronization with other computer started before it was finished on the first one. So, it is due to race conditions between clients.

**Comment by nlmarco** [comment]
I ran the above bash script multiple times (enabling/commenting out different cases in it labelled "1st", "2nd" and "3rd case"), but unfortunately was not able to reproduce any eternal "collisions of collisions of collisions ..." scenario.

Still, following your hint "generated hashes for collision files are not unique enough" I changed the code in IOUtil.createCollisionFile(...) to produce *extremely* unique names: Before, it was just the timestamp - now there's a UUID-like (differently encoded though) random part added after the timestamp.

Please re-open this ticket, if the problem still happens in 0.9.9.
